server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Karnantcs/config-server
          username: karuppuswamybe@gmail.com
          password: karnan5U

management:
  endpoints:
    web:
      exposure:
        include: "health"
